; PlatformIO project configuration
; https://docs.platformio.org/page/projectconf.html

[platformio]
test_dir = ../tests/firmware

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.1.0
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

build_flags =
    -D CORE_DEBUG_LEVEL=3